version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
      - PASSWORD=rootctd         # ඔබ කැමති Password එක
      - SUDO_PASSWORD=sudoctd    # Terminal sudo password එක
    volumes:
      - ./config:/config
    ports:
      - "8443:8443"
    restart: unless-stopped
